Acme\StoreBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Acme\StoreBundle\Entity\ProductRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        userid:
            type: integer
        name:
            type: string
            length: '100'
        category:
            type: string
            lengh:  '11'
        price:
            type: decimal
        status:
            type: integer
        description:
            type: text
        image:
            type: string
    lifecycleCallbacks: {  }
