order_detail:
    pattern:  /order/detail/{id}
    defaults: { _controller: AcmeStoreBundle:Default:orderDetail }

order_delete:
    pattern:  /order/delete/{id}
    defaults: { _controller: AcmeStoreBundle:Default:orderDelete }

acme_store_orders:
    path:     /store/orders
    defaults: { _controller: AcmeStoreBundle:Default:orders }

status:
    pattern:  /store/status
    defaults: { _controller: AcmeStoreBundle:Default:status }

search:
    pattern:  /search
    defaults: { _controller: AcmeStoreBundle:Default:search}
    
sorting:
    pattern:  /store/sorting
    defaults: { _controller: AcmeStoreBundle:Default:sorting }

acme_store:
    path:     /store/
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_product_list:
    pattern:  /product/{page}
    defaults: { _controller: AcmeStoreBundle:Default:list,page:1 }

add:
    pattern:  /store/add
    defaults: { _controller: AcmeStoreBundle:Default:add }

addproduct:
    pattern:  /addproduct
    defaults: { _controller: AcmeStoreBundle:Default:addproduct }

edit:
    pattern:  /store/edit/{id}
    defaults: { _controller: AcmeStoreBundle:Default:edit }

delete:
    pattern:  /store/delete/{id}
    defaults: { _controller: AcmeStoreBundle:Default:delete }
