acme_team:
    resource: "@AcmeTeamBundle/Resources/config/routing.yml"
    prefix:   /

acme_info:
    resource: "@AcmeInfoBundle/Resources/config/routing.yml"
    prefix:   /info

acme_home:
    resource: "@AcmeHomeBundle/Resources/config/routing.yml"
    prefix:   /

acme_image:
    resource: "@AcmeImageBundle/Resources/config/routing.yml"
    prefix:   /image

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
acme_category:
    resource: "@AcmeCategoryBundle/Resources/config/routing.yml"
    prefix:   /

acme_footer:
    resource: "@AcmeFooterBundle/Resources/config/routing.yml"
    prefix:   /footer    


