acme_home:
    path:     /
    defaults: { _controller: AcmeHomeBundle:Default:index }

aboutus:
    path:    /aboutus/
    defaults: { _controller: AcmeHomeBundle:Default:aboutus }

services:
    path:    /services/
    defaults: { _controller: AcmeHomeBundle:Default:services }

portfolio:
    path:    /portfolio/
    defaults: { _controller: AcmeHomeBundle:Default:portfolio }

blog:
    path:    /blog/
    defaults: { _controller: AcmeHomeBundle:Default:blog }

pricing:
    path:    /pricing/
    defaults: { _controller: AcmeHomeBundle:Default:pricing }

shortcodes:
    path:    /shortcodes/
    defaults: { _controller: AcmeHomeBundle:Default:shortcodes }

contactus:
    path:   /contactus/
    defaults: { _controller: AcmeHomeBundle:Default:contactus }
    
news:
    path:    /news/
    defaults: { _controller: AcmeHomeBundle:Default:news }
    
products:
    path:   /products/
    defaults: { _controller: AcmeHomeBundle:Default:products }
    
contact_sendEmail:
    path:   /contact/sendEmail
    defaults: { _controller: AcmeHomeBundle:Default:sendEmail }
    
