Acme\InfoBundle\Entity\Testimonials:
    type: entity
    table: null
    repositoryClass: Acme\InfoBundle\Entity\TestimonialsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        post:
            type: string
            length: 255
        description:
            type: text
        image:
            type: string
            length: 255    
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
