Acme\HomeBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: Acme\HomeBundle\Entity\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        city:
            type: string
            length: 255
        email:
            type: string
            length: 255
        message:
            type: text
    lifecycleCallbacks: {  }
