parameters:
#    acme_team.example.class: Acme\TeamBundle\Example

services:
#    acme_team.example:
#        class: %acme_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
