acme_user_edit:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeUserBundle:Default:edit }

acme_user_delete:
    pattern:  /delete/{id}
    defaults: { _controller: AcmeUserBundle:Default:delete }

acme_user_status:
    pattern:  /status
    defaults: { _controller: AcmeUserBundle:Default:status }
    
acme_user:
    path:     /
    defaults: { _controller: AcmeUserBundle:Default:index }

